# Generated by Django 3.2.16 on 2022-11-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='link_id',
            field=models.CharField(db_index=True, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
