apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fishy-sc-redis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fishy-sc-redis
  labels:
    app: fishy-sc-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: fishy-sc-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishy-sc-redis
  labels:
    app: fishy-sc-redis
spec:
  selector:
    matchLabels:
      app: fishy-sc-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: fishy-sc-redis
    spec:
      containers:
        - name: fishy-sc-redis
          image: redis
          command: ['redis-server', '--appendonly', 'yes']
          ports:
          - containerPort: 6379
            name: fishy-sc-redis
          volumeMounts:
          - name: redis
            mountPath: /data
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: fishy-sc-redis-pv-claim
