apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "quorum.fullname" . }}
    name: genesis-config
data:
  genesis-geth.json.tmpl: |-
      {
        "alloc": {
        {{ $scope := . }}
        {{ $length := len .Values.nodes }}
        {{ range $k, $v := .Values.nodes }}
          {{ $index := $k | substr 4 6 | int }}
          "%{{ include "quorum.fullname" $scope }}-node{{ $index }}-nodekeyaddress%": {
            "balance": "1000000000000000000000000000"
          }{{ if lt $index $length }},{{ end }}
        {{- end }}
        },
        "coinbase": "0x0000000000000000000000000000000000000000",
        "config": {
          "homesteadBlock": 0,
          "byzantiumBlock": 0,
          "constantinopleBlock": 0,
          "petersburgBlock": 0,
          "istanbulBlock": 0,
          "eip150Block": 0,
          "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "eip155Block": 0,
          "eip158Block": 0,
          "txnSizeLimit": 128,
          "maxCodeSizeConfig": [
            {
              "block": 0,
              "size": 128
            }
          ],
          "chainId": 1000,
          "isQuorum": true,
          "istanbul": {
            "epoch": 30000,
            "policy": 0
          }
        },
        "difficulty": "0x1",
        "extraData": "%ISTANBUL_EXTRA_DATA%",
        "gasLimit": "0xE0000000",
        "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
        "nonce": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "timestamp": "0x00"
      }
